function sumone(x, y, z) {
    return ((x*y)+z);
}
// sumone(4,9);
let surya = sumone(2,12);
// console.log(surya);

let arr3 = [19,152,25];
console.log(sumone(...arr3));

// Try and Catch
// Try :  means b4 passing checking the code
// something which is going to throw logical error. 
// catch : catch will catch the error and we can write the error handling PaymentMethodChangeEvent.

// finally : i will be running th code regardless of the situation.means regardless of tjhe error / or not error.it s nt mandatory to write finally

// promise is divided into 3 categories:
// - pending
// - fullfilled
// - rejected

// Event loop or event queue
//whenever we want to create a promise we write new Promise
// async: write async where u want evything to get synchronized
//await : who has to wait, it is ur login page.